spring:
  data:
    mongodb:
      database: star-wars-db
      uri: mongodb://star-wars-db:A620jnvGiTakVHJCy6wOz8pUWYg24Bc6SJkhiFyEDyQflr2VsUUT73MbNlvcVS9YNxvSxDtmnqPAJKMHPHAaEw==@star-wars-db.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@star-wars-db@


springdoc:
  api-docs:
    path: /starwars-docs
